### ISSUE TITLE
Updating Macroquad Version

### ISSUE THREAD

**Issue by emadpres** [optozorax/egui-macroquad#40]
Hi

As far as I understood, this crate is designed to internally include `macroquad` as its own dependency (most probably to ensure nothings breaks) and therefore the user of `egui-macroquad` are not supposed to add both `macroquad` and `egui-macroquad` as dependencies.

Meaning, this is not going to work (it causes a panic in my case)
```toml
[dependencies]
macroquad = "0.4.5"  # or its variants, like { version = "0.4.5", default-features = false }
egui-macroquad = "0.15.0"
```

If so, what's the process of updating `egui-macroquad` to use more recent versions of `macroquad`? As of now, `egui-macroquad` depends on`macroquad 0.3.x` while `0.4.x` is out for a while.
